environment: production

title: Anna Fechtig
description: Anna Fechtig, media designer and creator of anything that is worth to be created.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.annafechtig.com # the base hostname & protocol for your site

gems:
  - jekyll-sitemap
  - jekyll-autoprefixer

collections:
  projects:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

about_text: |
  Hallo!
  My name is Anna and I’m a 3rd year Media design student at <a href="https://www.hdpk.de/de/startseite/" target="_blank" rel="noopener noreferrer">HDPK</a> in Berlin.

  I’m a dreamer, nature enthusiast, <span id="alpaga-toggle">alpaca owner</span> and creator of anything that i think is worth to be created.

  In the past, i had the chance to work at <a href="https://www.foodora.com/" target="_blank" rel="noopener noreferrer">Foodora</a> and <a href="http://www.anekdotboutique.com/" target="_blank" rel="noopener noreferrer">anekdotboutique</a>.
  I’m available all year for freelance work.

# Accounts settings
social_networks:
  - name: Instagram
    link: https://www.instagram.com/annalovesdonuts
    icon: instagram
  - name: Vimeo
    link: https://vimeo.com/user21665398
    icon: vimeo

email_address: anna.fechtig@t-online.de

google_analytics:
  site_id: UA-90032604-1

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed
