environment: production

title: Anna Fechtig
description: Anna Fechtig, freelance video creator, berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.annafechtig.com # the base hostname & protocol for your site

gems:
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      no_imprint_link: true

about_text: |
  Hallo!
  My name is Anna. I’m a filmmaker and video editor from Berlin.
  
   I’m a nature enthusiast, <span id="alpaga-toggle">alpaca owner</span> and creator of anything that i think is worth to be created.

  I’m available for freelance work.

# Accounts settings
social_networks:
  - name: Instagram
    link: https://www.instagram.com/annalovesdonuts
    icon: instagram
  - name: Vimeo
    link: https://vimeo.com/user21665398
    icon: vimeo

email_address: hello@annafechtig.com

google_analytics:
  site_id: UA-90032604-1

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed


