title: Anna Fechtig
description: Anna Fechtig
baseurl: "" # the subpath of your site, e.g. /blog
url: http://anna-fechtig.com # the base hostname & protocol for your site

gems:
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /project/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

social_networks:
  - name: Instagram
    link: https://www.instagram.com/annalovesdonuts
    icon: instagram
  - name: Vimeo
    link: https://vimeo.com/user21665398
    icon: vimeo

environment: production

# Google Analytics settings
# @TODO SET GOOGLE ANALYTICS IDS
google_analytics:
  site_id:
  analycator_app_id:

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed
