environment: production

title: Anna Fechtig
description: Anna Fechtig
baseurl: "" # the subpath of your site, e.g. /blog
url: http://anna-fechtig.com # the base hostname & protocol for your site

gems:
  - jekyll-sitemap
  - jekyll-autoprefixer

collections:
  projects:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Use two backslashes and indent the text with two spaces to add a linebreak.
about_text: >
  Hello! \\
    My name is Anna and I’m a 3rd year Media design student at
    <a href="https://www.hdpk.de/de/startseite/" target="_blank" rel="noopener noreferrer">HDPK</a>.

# Accounts settings
social_networks:
  - name: Instagram
    link: https://www.instagram.com/annalovesdonuts
    icon: instagram
  - name: Vimeo
    link: https://vimeo.com/user21665398
    icon: vimeo

email_address: anna.fechtig@t-online.de

# @TODO SET GOOGLE ANALYTICS IDS
google_analytics:
  site_id:
  analycator_app_id:

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed
